avantifellows/plio-frontend

- src/components/PlioQuestion.vue
- src/views/Player.vue
> Options persist | Marker Color Change | Done Button

- src/components/LoadingSpinner.vue
- src/components/PlioQuestion.vue
- src/views/Player.vue
Questions that have a difference of 500ms, 400ms or even 300ms work properly now.
After this fix, I didn't notice any bugs regarding question being missed out, or popping up again.
Also added loading screen to `play` page and to individual `modals`. Reason explained in my review
Will share a demo video on Plio Tech group, cannot attach videos here
> FIX: Better detection of question popup

- src/components/LoadingSpinner.vue
- src/components/PlioQuestion.vue
- src/views/Player.vue
- spinner style change
- check every 500ms instead of 10ms
- minor bugs
> Bug fixes from last merge

- package.json
- src/components/PlioQuestion.vue
- src/main.js
Registered a global component for fontawesome.
Wherever a particular icon is required, it can be imported in that particular vue file and used.
Earlier the whole css file was being imported. Now only the specific icons can be imported
> NEW: fontawesome icons/svgs can be used as components now

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- .github/PULL_REQUEST_TEMPLATE.md
1. Issue templates: bug report, feature request and task
2. Pull request template
> GitHub templates

- src/App.vue
Fixes #92 
Just a follow up to #93 - position of the switcher changed for the player. This fixes that. 
Tested locally and on staging - for home and player
> FIX: added change to keep position of switcher in player too

- package.json
- src/main.js
Fixes -- 
Setting up primevue, importing and using it in our app instance. [source](https://primefaces.org/primevue/showcase/#/setup)
Setting up tailwind, importing the main css files in our app instance. [source](https://tailwindcss.com/docs/installation)
Tested locally by using a button provided by PrimeVue.
Took proposed design specs from the CC's design team, applied it to the main css file of PrimeVue's button element and the changes rendered properly.
Was also able to override the button's properties using tailwind's css directives as well
> NEW: setting up primevue and tailwind

- package-lock.json
- postcss.config.js
- src/index.css
- src/main.js
- tailwind.config.js
Fixes #113 
Followed the [installation guide](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) to install Tailwind correctly.  
Tested the classes of Tailwind in a dummy component
> FIX: tailwind installation

- src/components/UI/Text/InputText.vue
- src/pages/Editor.vue
- src/services/API/Plio.js
> InputText cleanup, update + fetch plio details from backend, periodic updates, status var

- src/pages/Editor.vue
> FIX: Creator bugs

- src/pages/Login.vue
- src/router/index.js
Fixes #144 
Modifies the `router/index.js` and `Login.vue` to pass in the page to the redirect to along with the params.
P.S. most of the marked changes are from the effects of linting.
Tested locally by logging out, trying to visit player page, being sent to the login page and after logging in, being redirected to the player page.
> FIX: redirect user back to where they came to login page

- .env.example
- src/App.vue
- src/components/UI/LocaleSwitcher.vue
- src/pages/ABTesting.vue
- src/pages/Login.vue
- src/services/API/Endpoints.js
- src/services/API/User.js
- src/services/Config/User.js
- src/services/Config/User.vue
- src/services/Localisation/i18n.js
- src/store/modules/auth.js
Fixes #161 
Fixes #162 
Fixes #146 
Tested locally.
> Cleanup user config and experiments

- src/components/UI/Player/VideoPlayer.vue
- src/pages/Editor.vue
Fixes #186 
Fixes #185 
- The plyr element being removed was turning up null in some cases and throwing an error
- The ring color of the buttons was blue which seemed very odd when clicking the buttons.
- Tested locally
> Fixes minor bugs with the editor

- package-lock.json
- package.json
- src/App.vue
- src/components/Editor/ItemEditor.vue
- src/components/UI/Text/URL.vue
- src/main.js
- src/pages/Login.vue
- src/pages/Player.vue
- src/services/API/RootClient.js
- src/services/Functional/ErrorHandling.js
> Error states

- src/App.vue
- src/pages/Editor.vue
- src/pages/Home.vue
> FIX: switching workspaces did not update the plio list in some cases + don't fetch plio list if user is not approved

- src/components/UI/Text/URL.vue
- src/pages/Editor.vue
> FIX: mobile visual bugs - big add item button + plio URL

- .github/workflows/deploy_to_ecs_prod.yml
- .github/workflows/deploy_to_ecs_staging.yml
- README.md
1. Badges updated in readme for build statuses
2. Corrected workflow names and in sync with backend workflows
> Open source badges

- src/assets/locales/en.js
- src/assets/locales/hi.js
- src/pages/Login.vue
> FIX: warning - only indian numbers supported

- src/components/Collections/Table/Table.vue
- src/components/UI/Text/InputNumber.vue
- src/components/UI/Text/InputText.vue
- src/components/UI/Text/Textarea.vue
> Removes autocomplete from form input areas

- src/components/Collections/Table/Table.vue
> FIX: analyse button padding bug

- src/App.vue
- src/components/Collections/ListItems/PlioListItem.vue
- src/components/Collections/Table/Table.vue
- src/components/UI/Navigation/Paginator.vue
- src/main.js
- src/pages/Login.vue
- src/router/index.js
> UI bugs 0.1.3

- src/App.vue
- src/pages/Login.vue
> FIX: temporarily remove phone login

- src/components/UI/Buttons/IconButton.vue
> FIX: added spacing between the icon and the text in an icon_button

- src/components/UI/Slider/SliderWithMarkers.vue
> FIX: slider and markers working on firefox

- .gitignore
- src/components/UI/Skeletons/VideoSkeleton.vue
- src/pages/Player.vue
Fixes #288 
- removed image from player placeholder to use a block
> New video skeleton

- src/App.vue
- src/components/Collections/ListItems/PlioListItem.vue
- src/pages/Dashboard.vue
- src/pages/Editor.vue
- src/pages/Home.vue
- src/pages/Login.vue
- src/pages/Player.vue
Fixes #299 
- Adds identity management
- Adds events as discussed in the tracking plan v1
> Mixpanel setup for v1 events

- .github/PULL_REQUEST_TEMPLATE.md
- src/App.vue
- src/components/UI/LocaleSwitcher.vue
- src/components/UI/WorkspaceSwitcher.vue
- src/pages/Home.vue
- src/pages/Login.vue
- src/pages/Player.vue
> Adds Mixpanel user properties and super properties

- src/components/Items/Question/Body.vue
- src/components/Items/Question/Header.vue
- src/components/Player/ItemModal.vue
- src/pages/Editor.vue
> Preview on editor

- src/assets/locales/en.js
- src/assets/locales/hi.js
- src/components/Items/Question/Body.vue
- src/components/Items/Question/Footer.vue
- src/components/Items/Question/Header.vue
- src/components/Player/ItemModal.vue
- src/components/UI/Buttons/IconButton.vue
- src/pages/Editor.vue
- src/pages/Player.vue
> Minimize item

- src/components/Player/ItemModal.vue
- src/components/UI/Alert/ImageUploaderDialog.vue
- src/components/Vue2PortedPackages/VueImageUploader.vue
> FIX: after deleting, sometimes images could not be re-uploaded

- README.md
- src/assets/locales/en.js
- src/assets/locales/hi.js
- src/pages/Dashboard.vue
> FIX: REDO of Minor dashboard issues

- src/pages/Home.vue
- src/router/index.js
> FIX: org prop was not being propogated to the dashboard component

- src/components/Items/Question/Body.vue
> FIX: alignment consistency issue

- .github/workflows/ci.yml
- jest.init.js
- tests/unit/pages/Player.spec.js
> NEW: initialised mixpanel, router for test cases + player initial testcase

- jest.init.js
- package.json
- src/components/Items/Question/Footer.vue
- src/components/Player/ItemModal.vue
- tests/unit/components/Collections/ListItems/PlioListItem.spec.js
- tests/unit/components/Collections/Table/Table.spec.js
- tests/unit/components/Editor/ItemEditor.spec.js
- tests/unit/components/Editor/QuestionTypeDropdown.spec.js
- tests/unit/components/Items/Question/Body.spec.js
- tests/unit/components/Items/Question/Footer.spec.js
- tests/unit/components/Items/Question/Header.spec.js
- tests/unit/components/Player/ItemModal.spec.js
- tests/unit/components/UI/Alert/DialogBox.spec.js
- tests/unit/components/UI/Alert/ImageUploaderDialog.spec.js
- tests/unit/components/UI/Text/InputText.spec.js
- tests/unit/components/UI/Text/TimeInput.spec.js
- tests/unit/components/UI/Text/URL.spec.js
Fixes #356 
- changes the color to make proceed button distinguishable from submit
> NEW: proceed button color

- jest.init.js
- package-lock.json
- package.json
- src/components/Editor/ItemEditor.vue
- src/components/Editor/QuestionTypeDropdown.vue
- src/components/Items/Question/Footer.vue
- src/components/Player/ItemModal.vue
- src/components/UI/Alert/DialogBox.vue
- src/components/UI/Navigation/Paginator.vue
- src/components/UI/Text/URL.vue
- src/main.js
- tests/unit/components/Collections/ListItems/PlioListItem.spec.js
- tests/unit/components/Collections/Table/Table.spec.js
- tests/unit/components/Editor/ItemEditor.spec.js
- tests/unit/components/Editor/QuestionTypeDropdown.spec.js
- tests/unit/components/Items/Question/Body.spec.js
- tests/unit/components/Items/Question/Footer.spec.js
- tests/unit/components/Items/Question/Header.spec.js
- tests/unit/components/Player/ItemModal.spec.js
- tests/unit/components/UI/Alert/DialogBox.spec.js
- tests/unit/components/UI/Alert/ImageUploaderDialog.spec.js
- tests/unit/components/UI/Navigation/Paginator.spec.js
- tests/unit/components/UI/Player/VideoPlayer.spec.js
- tests/unit/components/UI/Slider/SliderWithMarkers.spec.js
- tests/unit/components/UI/Text/InputNumber.spec.js
- tests/unit/components/UI/Text/InputText.spec.js
- tests/unit/components/UI/Text/Textarea.spec.js
- tests/unit/components/UI/Text/TimeInput.spec.js
- tests/unit/components/UI/Text/URL.spec.js
- tests/unit/components/Vue2PortedPackages/VueImageUploader.spec.js
> FIX: more tests

- src/App.vue
> NEW: mixpanel phone fixed

- package-lock.json
- package.json
- src/App.vue
- src/pages/Player.vue
- src/router/index.js
- src/services/API/Endpoints.js
- src/services/API/User.js
Fixes #364
Depends on [this PR](https://github.com/avantifellows/plio-backend/pull/207)
> Avanti auth override support

- src/router/index.js
> FIX: users closing the tab while being in org workspace will now land on that workspace after coming back

- src/pages/Player.vue
- src/router/index.js
- src/services/API/Endpoints.js
- src/services/API/User.js
> FIX: refactored third party auth according to new logic

- src/components/Items/Question/Body.vue
- src/components/Items/Question/Header.vue
- src/components/Player/ItemModal.vue
> FIX: minor UI fixes

- src/App.vue
> FIX: minor bugs

- src/pages/Editor.vue
- src/pages/Player.vue
> FIX: loading spinner when adding questions + multiple marker on player fix

- src/App.vue
> FIX: one UI bug and one functional bug

- src/pages/Player.vue
- src/store/modules/auth.js
> FIX: in SSO, activeWorkspace info was not being set in the first call

- src/pages/Player.vue
- src/router/index.js
> Uses org prop instead of value from backend for SSO

- src/App.vue
- src/components/App/WorkspaceSwitcher.vue
> Disable workspace switcher in pending mode

- src/pages/Home.vue
> FIX: switching workspaces when in page other than first page

- src/router/index.js
> Add page titles

- src/App.vue
- src/components/Collections/ListItems/PlioListItem.vue
- src/components/Collections/Table/Table.vue
- src/pages/Home.vue
- tests/unit/components/Collections/Table/Table.spec.js
> Enable searching on pressing enter in the search box

- src/services/API/RootClient.js
> DEL: removed unused old aws cognito code for getting analytics api token.

- src/components/Items/Scorecard.vue
> Round accuracy to nearest integer

- src/App.vue
> Disable create button while the home page is loading

- src/pages/Embeds/Plio.vue
Fixes #514 
- ~[ ] Test Responsiveness~
- ~[ ] Cross-Browser Testing~
- ~[ ] Local Language Support~
- ~[ ] Wrote tests~
- ~[ ] Check for bundle size [here](https://bundlephobia.com/) if adding a package~
- ~[ ] Images have `alt` attributes~
- ~[ ] Any `target="_blank"` links have `rel="noopener"`~
- ~[ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.~
- ~[ ] Tested on an actual physical phone~
> FIX: bug resulting in 400 in `events/` call

- src/components/UI/Alert/DialogBox.vue
- src/pages/Editor.vue
- src/services/API/RootClient.js
- tests/unit/components/UI/Alert/DialogBox.spec.js
> Added configurable close button to dialog box

- src/pages/Editor.vue
> Changed the positions of the draft and updated_at elements based on the new design

- .github/workflows/ci.yml
- docs/CYPRESS.md
1. Removed duplicate variables
2. Removed GitHub environment. Directly picking from organization env variables
> CI cleanups

- .github/workflows/deploy_to_ecs_prod.yml
- .github/workflows/deploy_to_ecs_staging.yml
> Updated workflow to include timestamp in the image tag

- src/services/API/ErrorHandling.js
> Stop loading if accessing editor for plio where access is denied

- docs/PRE-COMMIT.md
Fixes #592 
Commands for Pre-commit installation and usage are added in the doc.
</strike>
</strike>
</strike>
</strike>
> Updated Pre-Commit.md

- src/components/UI/Slider/SliderWithMarkers.vue
Fixes #586 
Modified the `isMarkerVisible` function so that the user can see the marker till the end of the video and at all zoom levels.
> Dragging questions to the end of the video makes the marker disappear

- src/components/UI/Text/InputNumber.vue
Fixes #602 
The `localvalue.length`  was returning undefined as it was not being converted into a string.
`.toString` function is added to the `localValue` in `keypress` function in `InputNumber.vue`.
`type` of `<input` is changed to `type`  which is a prop and has `default:"tel"` as there were many trailing zeros and the eventual phone number length was going way beyond 10 and it was still marked valid .
`If` condition is added in `keypress` so that any character is not accepted as input.
> Phone number digits can not be entered more than 10 and 0 input invalid

- src/pages/Home.vue
> Prevents empty rows from being shown when transitioning to workspace with no plios

- src/pages/Embeds/Plio.vue
Fixes #644 
Please read the details in the issue!
> inverted player timer

- src/App.vue
- src/components/Collections/ListItems/PlioListItem.vue
- src/pages/Home.vue
- src/router/index.js
> allow copy from one workspace to another
